package uk.ac.tees.mad.foodreview.ui.login

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch
import uk.ac.tees.mad.foodreview.domain.repository.AuthRepository
import uk.ac.tees.mad.foodreview.utils.PreferenceManager
import uk.ac.tees.mad.foodreview.utils.mapAuthError

class LoginViewModel(private val authRepository: AuthRepository ,
 private val  preferenceManager: PreferenceManager) : ViewModel(){

    private val _loginUiState = MutableStateFlow(LoginUiState())
    val loginUiState : StateFlow<LoginUiState> = _loginUiState.asStateFlow()


    fun onEmailChange(email : String){
        _loginUiState.update {
            it.copy(
                email = email
            )
        }
    }

    fun onPasswordChange(password : String){
        _loginUiState.update {
            it.copy(
                password = password
            )
        }
    }

    fun onVisibilityToggle(value : Boolean){
        _loginUiState.update {
            it.copy(
                isPasswordVisible = value
            )
        }
    }

    fun onLoginClick(){
        viewModelScope.launch {
            _loginUiState.update {
                it.copy(
                    isLoading = true
                )
            }

            authRepository
                .signIn(email = _loginUiState.value.email , password = _loginUiState.value.password)
                .onSuccess { success ->
                    preferenceManager.setLoggedIn(true)
                    preferenceManager.setEmail(email = _loginUiState.value.email )
                    preferenceManager.setLastLogin(formatDate(System.currentTimeMillis()))
                    _loginUiState.update {
                        it.copy(
                            isLoading = false,
                            isLoginSuccess = true
                        )
                    }
                }
                .onFailure { error->
                    _loginUiState.update {
                        it.copy(
                            error = mapAuthError(error),
                            isLoading = false ,
                            isLoginSuccess = false
                        )
                    }
                }
        }
    }

    fun formatDate(timestamp: Long): String {
        val sdf = java.text.SimpleDateFormat("dd.MM.yyyy", java.util.Locale.getDefault())
        return sdf.format(java.util.Date(timestamp))
    }

}


/**
 * _loginState.update{}
 * here .update is an extension function of MutableStateFlow()
 * it is used to update the current value
 *
 * it.copy()
 * .copy() is autogenerated function for the data classes which behind the scene take the
 * current object and keeps all the value same and replaces new values and creates a new object
 * and return the new object
 *
 * fun copy(email , password):LoginUiState
 * compiler generate this code for data classes
 */